version: '3.8'

services:
  company_service:
    container_name: companies
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Company
    ports:
      - '5451:5432'
    volumes:
      - CompanyData:/var/lib/postgresql/data
    networks:
      - dts_network

  user_service:
    container_name: users
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: User
    ports:
      - '5452:5432'
    volumes:
      - UserData:/var/lib/postgresql/data
    networks:
      - dts_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - dts_network


volumes:
  CompanyData: {}
  UserData: {}

networks:
  dts_network:
    driver: bridge
