spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: serxan.babayev.06@gmail.com
    password: klmp yxwd jtdz ptmn
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: dtsservice
  datasource:
    first:
      url: jdbc:postgresql://company_service:5432/Company
      #url: jdbc:postgresql://localhost:5451/Company

      username: root
      password: root
    second:
      #url: jdbc:postgresql://localhost:5452/User
      url: jdbc:postgresql://user_service:5432/User
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      #host: localhost

      port: 6379

cloudinary:
  cloud_name: dgiumshwd
  api_key: 384648233811973
  api_secret: bsuE4WS9TVqHmE5EffLEG311rqw
